server:
  port: 8000

spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database: h2
    show-sql: true

logging:
  level:
    sql: debug

#jwt
jwt:
  secret: '3lk23mklz9scbaslkgbkl124lq4k6lk26nlkn'
  expiration: 3600000

# cors 설정
cors:
  allowed-origins: 'http://127.0.0.1:8000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600
